name: "main-github-actions-workflow"
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      # Build and publish to pipy
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          scripts: dist/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build and publish
        run: |
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload dist/* --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
